version: '3'
services:
  frontend:
    # build: ./car-management-app
    image: ghcr.io/patagan/mercedes_task/car-management-app:latest
    ports:
      - "4200:80"
  backend:
    #build: ./mercedes-kfz
    image: ghcr.io/patagan/mercedes_task/mercedes-kfz:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/kfz
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    restart: always
    entrypoint: /bin/sh -c 'sleep 15 && java -jar /app/spring-boot-application.jar'
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: kfz
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    # Enable volumes to keep the data in a back up
    #volumes:
    #  - ./mysql-data:/var/lib/mysql
