version: '3'
services:
  backend:
    build: ./kfz
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/kfz
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: kfz
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    #volumes:
    #  - ./mysql-data:/var/lib/mysql
