name: CI/CD Pipeline for car-management-app

on:
  push:
    branches:
      - main
permissions: write-all
jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        working-directory: ./car-management-app
        run: npm install

      - name: Run Unit Tests
        working-directory: ./car-management-app
        run: npm test
  deploy-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        working-directory: ./car-management-app
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/car-management-app:latest .

      - name: Push Docker image to GitHub Packages
        run: docker push docker.pkg.github.com/${{ github.repository }}/car-management-app:latest

  build-backend:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle
        working-directory: ./mercedes-kfz
        run: ./gradlew build
  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        working-directory: ./mercedes-kfz
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/mercedes-kfz:latest .

      - name: Push Docker image to GitHub Packages
        run: docker push docker.pkg.github.com/${{ github.repository }}/mercedes-kfz:latest

