name: CI/CD Pipeline for car-management-app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    working-directory: ./car-management-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: cd npm install

      - name: Build
        run: npm test

      - name: Deploy to Hosting Service
        # Add deployment steps here, e.g., deploying to Firebase, AWS, etc.
